services:
  postgres:
    container_name: Postgres-Database
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DOMAIN: ${POSTGRES_DOMAIN}
    volumes:
      - ./Postgres_data:/var/lib/postgresql
    restart: always
    networks:
      - olytech_net

  redis:
    container_name: Redis-Cache
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./Redis_data:/data
    restart: always
    networks:
      - olytech_net

volumes:
  olytech_data:

networks:
  olytech_net: